<a href="https://colab.research.google.com/github/LivingstonTardzenyuy/Deep-Learning-with-TensorFlow/blob/main/00_tensorflow_fundamentatls.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we're going to cover some of the most fundamental concepts of tensors using TensorFlow

More specifically, we're going to cover:

* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* Using @tf.function ( a way to speeed up your regular Python functions)
* Using GPUs with TensorFlow(or TPUs)

# Introduction to Tensors

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.17.1


In [2]:
# Create tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor(ndim stands for number of dimensions)
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
#check dimension of our vector.
vector.ndim

1

In [6]:
# create a matrix

matrix = tf.constant([[10, 7],
                      [7, 10]
                      ])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# Create another matrix

another_matrix = tf.constant([[10., 7],
                              [3., 2.],
                              [8., 9.]],
                             dtype = tf.float16
                             )

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
# what is the number of dimensions of another_matrix.

another_matrix.ndim

2

In [10]:
# Let's create a tensor.

tensor = tf.constant([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]],

    [[13, 14, 15],
     [16, 17, 18]]
])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

What we've created so far:

* Scalar: A single number
* Vector: a number with direction
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (where n can be any number, 0-dimensional tensor is a scalar, 1-dimensional tensor is a vector)

# Creating a tensor with tf.Variable

In [12]:
# Create the same tensor with tf.variable as above.

changable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
# Let's try change one of the elements in our changable tensor
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

# Creating Random tensors

Random tensors are tensors that contains some arbituary random numbers.

In [14]:
# Create two random(but the same) tensor.
random_1 = tf.random.Generator.from_seed(42)  # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)

random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

#Shuffle the order of elements in a tensor

In [15]:
# Shuffle a tensor

not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])

# Shuffle our non-shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [16]:
 not_shuffled.shape

TensorShape([3, 2])

Other ways to make tensors

In [17]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [18]:
tf.zeros([5,5])

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

### Turn numpy arrays into tensors
The main d/f b/t Numpy arrays and Tensors is that that tensors can be run on a GPU computing

In [19]:

import numpy as np
numpy_A = np.arange(1,25, dtype=np.int32)
numpy_A

# X = tf.constant(some_matrix)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [20]:
A = tf.constant(numpy_A, shape=(2,3,4))
B = tf.constant(numpy_A)

A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Getting information from our Tensors

When dealing with tensors we will use the following

  * Shape
  * Rank
  * Axis or dimension
  * Size

In [21]:
# Creating a 4 tensor

rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [22]:
 rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [23]:
# Get various attributes of our tensor.
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along the 0 axis: ", rank_4_tensor.shape[0])
print("Elements along the last axis: ", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements in our tensor:  120


## Indexing tensors

In [24]:
# Get the first 2 elements of each dimension..
rank_4_tensor[:2, :2, :2, :2]

# rank_4_tensor = tf.zeros(shape=[2,3,4,5])

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [25]:
# Create a rank 2 tensor with 2 dimensions

rank_2_tensor = tf.constant([[10,7],
                             [3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [26]:
#Get the last item of each our rank 2 tensor.
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [27]:
# Add in extra dimensions to our rank 2 tensor

rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [28]:
  tf.expand_dims(rank_2_tensor, axis=0)   # expand the 0-axis....

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manipulating tensors (tensor operations)

** Basic operations

In [29]:
tensor = tf.constant([[10,7], [3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [30]:
# Multiplication also works

tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [31]:
# Subtraction

tensor -10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [32]:
# Division

tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [33]:
# We can use the tensorflow build in function.
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

# Matrix Multiplication

In ML, matrix multiplication is one of the most commond task

In [34]:
# matrix multiplication in tensorflow.

print(tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [35]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [36]:
# Try to matrix multply tensors of same shape.

X = tf.constant([[2,5],
                 [7,9],
                 [8,4]])

Y = tf.constant([[6,8],
                 [2,5],
                 [7,3]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 5],
        [7, 9],
        [8, 4]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[6, 8],
        [2, 5],
        [7, 3]], dtype=int32)>)

In [37]:
tf.matmul(X,Y)

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [ ]:
# Let's change the shape of Y

Y = tf.reshape(Y, shape=(2,3))
Y

In [ ]:
tf.matmul(X,Y)

In [ ]:
tf.transpose(X), tf.reshape(X, shape=(2,3))

In [ ]:
# Try matrix multiplication with transpose rather than reshape.

tf.matmul(tf.transpose(tf.reshape(X, shape=([2,3]))), Y)

**The dot product**

Matrix multiplication is also referred to as the dot product.

You can perform matrix multiplication using:

* `tf.matmul()`
* `tf.tensordot()`

In [ ]:
# Perform the dot product on X and Y (requires X or Y to be transpose)
tf.tensordot(X, Y, axes=1)

In [ ]:
# Check the values of Y, reshape Y and transposed Y

print("Normal Y: ")
print(Y, "\n")

print("Y reshaped to (2,3): ")
print(tf.reshape(Y, (2,3)), "\n")

print("Y transposed: ")
print(tf.transpose(Y))

In [ ]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 37,  51,  19],
       [ 87, 119,  41],
       [ 68,  92,  28]], dtype=int32)>

# Chaningin the datatype of a tensor

In [38]:
# Create a new tensor with a default datatype (float32)

B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [39]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [40]:
# Change from float32 to float16 (reduced precision)
B = tf.cast(B, dtype=tf.float16)
D, D.dtype

NameError: name 'D' is not defined

In [41]:
# Change from int32 to float 32.
E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

# Aggregating tensors

Aggreating tensors = condencing them from multiple values down to a smaller amount of values.


In [45]:
# Get the absolute values

D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [46]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following type of aggregation

* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [47]:
# Getting the minimum

tensor = tf.constant([10, 5, 2, 0, -6, 11, 60])
tf.reduce_min(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=-6>

In [48]:
# Getting the maximum.
tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=60>

In [49]:
# Get the mean of a tensor.

tf.reduce_mean(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=11>

In [50]:
# Get the sum of a tensor.

tf.reduce_sum(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=82>

In [54]:
tensor

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([10,  5,  2,  0, -6, 11, 60], dtype=int32)>

In [57]:
# Get the variance of a tensor  E = tf.cast(E, dtype=tf.float32) # Convert to float 32

tensor_float = tf.cast(tensor, dtype=tf.float32)
tf.math.reduce_variance(tensor_float)

<tf.Tensor: shape=(), dtype=float32, numpy=417.91837>

In [59]:
tf.reduce_std(tensor_float)

AttributeError: module 'tensorflow' has no attribute 'reduce_std'