<a href="https://colab.research.google.com/github/LivingstonTardzenyuy/Deep-Learning-with-TensorFlow/blob/main/Einsum_Operator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf

In [ ]:
A = np.array([
    [2,6,5,2],
    [2,-2,2,3],
    [1,5,4,0]
])

B = np.array([
    [2,9,0,3,0],
    [3,6,8,2,2],
    [1,3,5,0,1],
    [3,0,2,0,5]
])

print(A.shape)
print(B.shape)

(3, 4)
(4, 5)


In [ ]:
print(np.matmul(A,B))  # multiplying A and B

[[33 69 77 18 27]
 [ 9 12  0  2 13]
 [21 51 60 13 14]]


In [ ]:
print("Einsum C=: \n")
print(np.einsum("ij,jk -> ik", A,B))

Einsum C=: 

[[33 69 77 18 27]
 [ 9 12  0  2 13]
 [21 51 60 13 14]]


In [ ]:
A = np.array([
    [2,6,5,2],
    [2,-2,2,3],
    [1,5,4,0]
])

print("Einsum A=: \n")
print(np.einsum('ij -> j', A))
print("--------------------------")


Einsum A=: 

[ 5  9 11  5]
--------------------------


In [ ]:
x = tf.constant([[[2,3,4,5]]])
print(x.shape)
x_expanded = tf.expand_dims(x, axis=0)
print(x_expanded.shape)

(1, 1, 4)
(1, 1, 1, 4)


In [ ]:
t1 = [
    [1,2,3],
    [4,5,6]
    ]

t2 = [[7,8,9],
      [10,11,12]
      ]
print(tf.constant(t1).shape)
print(tf.constant(t2).shape)

tf.concat([t1,t2],1)

(2, 3)
(2, 3)


<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]], dtype=int32)>

In [2]:
indices = [[0],
           [1]]

params = [
    ['a','b'],
    ['c', 'd']
    ]
tf.gather_nd(params, indices)

<tf.Tensor: shape=(2, 2), dtype=string, numpy=
array([[b'a', b'b'],
       [b'c', b'd']], dtype=object)>

In [3]:
tf.gather_nd(params, indices)

<tf.Tensor: shape=(2, 2), dtype=string, numpy=
array([[b'a', b'b'],
       [b'c', b'd']], dtype=object)>

In [6]:
tensor_two_d = tf.constant(
    [[1,2,0],
     [3,5,1],
     [1,5,9],
     [2,6,5]
     ])
print(tensor_two_d)

tf.Tensor(
[[1 2 0]
 [3 5 1]
 [1 5 9]
 [2 6 5]], shape=(4, 3), dtype=int32)


In [8]:
tensor_ragged = tf.ragged.constant(tensor_two_d)
print(tensor_ragged.shape)

ValueError: TypeError: Scalar tensor has no `len()`
Traceback (most recent call last):

  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/ops.py", line 349, in __len__
    raise TypeError("Scalar tensor has no `len()`")

TypeError: Scalar tensor has no `len()`



In [11]:
 tensor_sparse = tf.sparse.SparseTensor(
     indices= [[1,1],[3,4]],
     values = [11,56],
     dense_shape = [3,5]
 )

tf.sparse.to_dense(tensor_sparse)

InvalidArgumentError: {{function_node __wrapped__SparseToDense_device_/job:localhost/replica:0/task:0/device:CPU:0}} indices[1] = [3,4] is out of bounds: need 0 <= index < [3,5] [Op:SparseToDense] name: 

In [12]:
 tensor_string = tf.constant(["hello", "i am", "a string"])
 print(tensor_string)

tf.Tensor([b'hello' b'i am' b'a string'], shape=(3,), dtype=string)


In [13]:
tf.strings.join(tensor_string, separator="+")

<tf.Tensor: shape=(), dtype=string, numpy=b'hello+i am+a string'>