<a href="https://colab.research.google.com/github/LivingstonTardzenyuy/Deep-Learning-with-TensorFlow/blob/main/Einsum_Operator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
import tensorflow as tf

In [3]:
A = np.array([
    [2,6,5,2],
    [2,-2,2,3],
    [1,5,4,0]
])

B = np.array([
    [2,9,0,3,0],
    [3,6,8,2,2],
    [1,3,5,0,1],
    [3,0,2,0,5]
])

print(A.shape)
print(B.shape)

(3, 4)
(4, 5)


In [4]:
print(np.matmul(A,B))  # multiplying A and B

[[33 69 77 18 27]
 [ 9 12  0  2 13]
 [21 51 60 13 14]]


In [5]:
print("Einsum C=: \n")
print(np.einsum("ij,jk -> ik", A,B))

Einsum C=: 

[[33 69 77 18 27]
 [ 9 12  0  2 13]
 [21 51 60 13 14]]


In [6]:
A = np.array([
    [2,6,5,2],
    [2,-2,2,3],
    [1,5,4,0]
])

print("Einsum A=: \n")
print(np.einsum('ij -> j', A))
print("--------------------------")


Einsum A=: 

[ 5  9 11  5]
--------------------------


In [10]:
x = tf.constant([[[2,3,4,5]]])
print(x.shape)
x_expanded = tf.expand_dims(x, axis=0)
print(x_expanded.shape)

(1, 1, 4)
(1, 1, 1, 4)


In [12]:
t1 = [
    [1,2,3],
    [4,5,6]
    ]

t2 = [[7,8,9],
      [10,11,12]
      ]
print(tf.constant(t1).shape)
print(tf.constant(t2).shape)

tf.concat([t1,t2],1)

(2, 3)
(2, 3)


<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]], dtype=int32)>