<a href="https://colab.research.google.com/github/LivingstonTardzenyuy/Deep-Learning-with-TensorFlow/blob/main/TensorFlow_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
tensor_one_d = tf.constant([2, 0, -3, 8, 90])
print(tensor_one_d)

tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int32)


In [5]:
tensor_two_d = tf.constant([
    [1, 2],
    [3,4],
    [4, 5],
    [6,7],
    ])
print(tensor_two_d)

tf.Tensor(
[[1 2]
 [3 4]
 [4 5]
 [6 7]], shape=(4, 2), dtype=int32)


In [7]:
tensor_three_d = tf.constant([
    [[1, 2, 0], [3,4, 0]],
    [[4, 5, 0], [6,7, 0]],
    [[7, 8, 0], [9,10, 0]],
    [[11, 12, 0], [13,14, 0]]
])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  4  0]]

 [[ 4  5  0]
  [ 6  7  0]]

 [[ 7  8  0]
  [ 9 10  0]]

 [[11 12  0]
  [13 14  0]]], shape=(4, 2, 3), dtype=int32)


In [8]:
print(tensor_three_d.shape)

(4, 2, 3)


In [12]:
tensor_four_d = tf.constant([
    [[[1,2,3]], [[4,5,6]]],
    [[[7,8,9]], [[10,11,12]]],
    [[[13,14,15]], [[16,17,18]]
]], dtype=tf.float32)
print(tensor_four_d)

tf.Tensor(
[[[[ 1.  2.  3.]]

  [[ 4.  5.  6.]]]


 [[[ 7.  8.  9.]]

  [[10. 11. 12.]]]


 [[[13. 14. 15.]]

  [[16. 17. 18.]]]], shape=(3, 2, 1, 3), dtype=float32)
