<a href="https://colab.research.google.com/github/LivingstonTardzenyuy/Deep-Learning-with-TensorFlow/blob/main/TensorFlow_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([2, 0, -3, 8, 90])
print(tensor_one_d)

tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
    [1, 2],
    [3,4],
    [4, 5],
    [6,7],
    ])
print(tensor_two_d)

tf.Tensor(
[[1 2]
 [3 4]
 [4 5]
 [6 7]], shape=(4, 2), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
    [[1, 2, 0], [3,4, 0]],
    [[4, 5, 0], [6,7, 0]],
    [[7, 8, 0], [9,10, 0]],
    [[11, 12, 0], [13,14, 0]]
])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  4  0]]

 [[ 4  5  0]
  [ 6  7  0]]

 [[ 7  8  0]
  [ 9 10  0]]

 [[11 12  0]
  [13 14  0]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
print(tensor_three_d.shape)

(4, 2, 3)


In [ ]:
tensor_four_d = tf.constant([
    [[[1,2,3]], [[4,5,6]]],
    [[[7,8,9]], [[10,11,12]]],
    [[[13,14,15]], [[16,17,18]]
]], dtype=tf.float32)
print(tensor_four_d)

tf.Tensor(
[[[[ 1.  2.  3.]]

  [[ 4.  5.  6.]]]


 [[[ 7.  8.  9.]]

  [[10. 11. 12.]]]


 [[[13. 14. 15.]]

  [[16. 17. 18.]]]], shape=(3, 2, 1, 3), dtype=float32)


In [ ]:
import numpy as np

In [ ]:
np_array = np.array([1,2,3,4])
print(np_array)

[1 2 3 4]


In [ ]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)


In [ ]:
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[2,4],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]], shape=(2, 4, 5, 5), dtype=float32)


In [ ]:
tf_fill = tf.fill(
    [2,5], 10
)
print(tf_fill)

tf.Tensor(
[[10 10 10 10 10]
 [10 10 10 10 10]], shape=(2, 5), dtype=int32)


In [ ]:
tf_ones = tf.ones(
    [2,5],
    dtype=tf.dtypes.float32,
    name=None
)

print(tf_ones)

tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(2, 5), dtype=float32)


In [ ]:
tensor = tf.constant([[1,2,3,4,5], [-2, -3, -4, -5, -6]])
tf.ones_like(tensor)

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)>

In [ ]:
random_tensor = tf.random.normal(
    [3,2],
    mean=100.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[101.44414  100.151886]
 [ 99.90847  100.028694]
 [ 98.97674   98.56722 ]], shape=(3, 2), dtype=float32)
